### ISSUE TITLE
SyntaxError: Unexpected token . @ sicap-parser/build/commands/licitatii.js:597

### ISSUE THREAD

**Issue by pax** [arhiva-sicap/sicap-parser#1]
instalat/built fără probleme, însă dup-aia:

    $sicap-parser licitatii -d 31-07-2020 -i licitatii -c 20
--- 
    <path/ro>/sicap-parser/build/commands/licitatii.js:597
    const transformFiscalCode = code => code?.replace(/ro/i, "") / 1 || 0;
                                            ^
    SyntaxError: Unexpected token .
        at new Script (vm.js:74:7)
        at createScript (vm.js:246:10)
        at Object.runInThisContext (vm.js:298:10)
        at Module._compile (internal/modules/cjs/loader.js:657:28)
        at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
        at Module.load (internal/modules/cjs/loader.js:599:32)
        at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
        at Function.Module._load (internal/modules/cjs/loader.js:530:3)
        at Module.require (internal/modules/cjs/loader.js:637:17)
        at require (internal/modules/cjs/helpers.js:20:18)

![image](https://user-images.githubusercontent.com/116795/92401475-6ef06e00-f136-11ea-8727-13201f6d15a9.png)

**Comment by sicap-user** [comment]
ce versiune de node folosesti?

optional chaining a fost introdus in node 14

**Comment by pax** [comment]
right, `v10.6.0`, de fapt și scrie în readme :)
*da ar putea să și atenționeze neatenții? :P

**Comment by pax** [comment]
am încercat și cu node 14.8 și 14.5, vezi #5
